apiVersion: apps/v1
kind: Deployment
metadata:
    name: prod-$CLR
spec:
    selector:
        matchLabels:
            app: example
            env: $CLR
    replicas: 1
    template:
        metadata:
            labels:
                app: example
                env: $CLR
        spec:
            containers:
                - name: example-api
                  imagePullPolicy: Always
                  image: kdalwadi28/nginx-stage
                  ports:
                      - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
    name: prod-$CLR
spec:
    type: NodePort
    selector:
        app: example
        env: $CLR
    ports:
        - port: 5000
          targetPort: 5000
          nodePort: 30009
