apiVersion: apps/v1
kind: Deployment
metadata:
    name: prod-green
spec:
    selector:
        matchLabels:
            app: example
            env: green
    replicas: 1
    template:
        metadata:
            labels:
                app: example
                env: green
        spec:
            containers:
                - name: example-api
                  imagePullPolicy: Never
                  image: dipak:latest
                  ports:
                      - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
    name: prod-green
spec:
    selector:
        app: example
        env: green
    ports:
        - port: 5000
          targetPort: 5000
