name: Docker Image CI

on:
#   push:
#     branches: [ dev ]
  pull_request_target:
    types:
      - closed

jobs:

  stage:
    if:  startsWith(github.head_ref, 'dev')
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: |
       GIT_COMMIT=$(git rev-parse --short HEAD)
       docker build ./app/ --tag kdalwadi28/nginx-stage 
       docker push kdalwadi28/nginx-stage
       docker rmi kdalwadi28/nginx-stage
       docker build ./app/ --tag kdalwadi28/nginx-stage:$GIT_COMMIT
       docker push kdalwadi28/nginx-stage:$GIT_COMMIT
       docker rmi kdalwadi28/nginx-stage:$GIT_COMMIT
    - uses: actions/checkout@v3       
    - name: Restart K8s Deployment
      run: |
#       export CLR=green
#       export BRANCH=stage
#       export PRT=30080
#       envsubst < ./manifest.yml | kubectl apply -f -
#       kubectl rollout restart deployment prod-green
 
  deploy:

    runs-on: self-hosted
    if:  startsWith(github.head_ref, 'stage')
    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: |
       GIT_COMMIT=$(git rev-parse --short HEAD)
       docker build ./app/ --tag kdalwadi28/nginx-prod --tag kdalwadi/nginx-prod:$GIT_COMMIT
       docker push kdalwadi28/nginx-prod
       docker rmi kdalwadi28/nginx-prod
       docker build ./app/ --tag kdalwadi28/nginx-prod:$GIT_COMMIT
       docker push kdalwadi28/nginx-prod:$GIT_COMMIT
       docker rmi kdalwadi28/nginx-prod:$GIT_COMMIT
       
    - uses: actions/checkout@v3
    - name: Restart K8s Deployment
      run: |
#       export CLR=blue
#       export BRANCH=prod
#       export PRT=30080
#       envsubst < ./manifest.yml | kubectl apply -f -
#       kubectl rollout restart deployment prod-blue
