name: Docker Image CI

on:
#   push:
#     branches: [ dev ]
  pull_request_target:
    types:
      - opened

jobs:

  stage:
    if:  startsWith(github.head_ref, 'dev')
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: |
       echo "$github.head_ref"
       docker build ./app/ --tag kdalwadi28/nginx-stage
       docker push kdalwadi28/nginx-stage
    - name: Restart K8s Deployment
      run: |
       export CLR=green
       envsubst < manifest | kubectl apply -f -
       kubectl rollout restart deployment prod-green
 
  deploy:

    runs-on: self-hosted
    if:  startsWith(github.head_ref, 'stage')
    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: |
       echo "$github.head_ref"
       docker build ./app/ --tag kdalwadi28/nginx-prod
       docker push kdalwadi28/nginx-prod

    - name: Restart K8s Deployment
      run: |
       export CLR=blue
       envsubst < manifest | kubectl apply -f -
       kubectl rollout restart deployment prod-blue
